[tool.poetry]
name = "ba-al"
version = "0.1.0"
description = ""
authors = ["Sven Nivera <sven1997@gmx.net>"]
readme = "README.md"
packages = [{include = "ba_al"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
